// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByb4b1zut6DVT82gf5jfFDBt7HcIb32bo',
    appId: '1:209980813947:web:b38d3c24efa70ebafb28de',
    messagingSenderId: '209980813947',
    projectId: 'polideportivoapp-d395f',
    authDomain: 'polideportivoapp-d395f.firebaseapp.com',
    storageBucket: 'polideportivoapp-d395f.firebasestorage.app',
    measurementId: 'G-SBXFXX707Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUL-UNJmRI7YP7G2lHVuRC2OoAWB38g9I',
    appId: '1:209980813947:android:f5f5c9ae0112002afb28de',
    messagingSenderId: '209980813947',
    projectId: 'polideportivoapp-d395f',
    storageBucket: 'polideportivoapp-d395f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAypRRF5TszPJ5EafldSRbQSO4bvY2m8PE',
    appId: '1:209980813947:ios:fb6eced6cf57c144fb28de',
    messagingSenderId: '209980813947',
    projectId: 'polideportivoapp-d395f',
    storageBucket: 'polideportivoapp-d395f.firebasestorage.app',
    iosBundleId: 'com.example.deportivov1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAypRRF5TszPJ5EafldSRbQSO4bvY2m8PE',
    appId: '1:209980813947:ios:fb6eced6cf57c144fb28de',
    messagingSenderId: '209980813947',
    projectId: 'polideportivoapp-d395f',
    storageBucket: 'polideportivoapp-d395f.firebasestorage.app',
    iosBundleId: 'com.example.deportivov1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByb4b1zut6DVT82gf5jfFDBt7HcIb32bo',
    appId: '1:209980813947:web:277457d975b14f2cfb28de',
    messagingSenderId: '209980813947',
    projectId: 'polideportivoapp-d395f',
    authDomain: 'polideportivoapp-d395f.firebaseapp.com',
    storageBucket: 'polideportivoapp-d395f.firebasestorage.app',
    measurementId: 'G-EKM4S29WDM',
  );
}
